### ISSUE TITLE
Multiple files for functions?

### ISSUE THREAD

**Issue by sbabicki** [UBC-MDS/kmeaningful#16]
Ask Tiff at office hours if it is better to have functions in seperate files for this milestone.

**Comment by trevorki** [comment]
Tiff says she has no preference for this milestone so we should do whatever is sensible for our project.
I think one file per function makes sense.

**Comment by sbabicki** [comment]
Do we want to split the files now? Or at the next milestone?

**Comment by trevorki** [comment]
Might as well do it now to save the future step.

**Comment by mikelynch416** [comment]
Agreed. I went ahead and moved them as part of pull request #17
