### ISSUE TITLE
2. Pick a topic

### ISSUE THREAD

**Issue by sbabicki** [UBC-MDS/kmeaningful#2]
Come up with a topic for your project. Discuss the topic with your TA or lab instructor and proceed only after your topic has been approved by one of them.

**Comment by mikelynch416** [comment]
Topic: Clustering

Functions: 
- function for implementing Kmeans clustering (fit and predict)
- function for preprocessing a generic dataset
- function for tuning threshold/other hyperparameters automatically
- function for doing dimensionality reduction automatically
- function for visualizing clusters according to PCA (2d or 3d)
-
