### ISSUE TITLE
Data types for all functions

### ISSUE THREAD

**Issue by trevorki** [UBC-MDS/kmeaningful#42]
It is unclear whether the data `X` should be in array or dataframe format. I have a strong preference here:

- It is **MUCH** easier to have `X` and `centers` as arrays and `labels` as a list while moving them around in `fit` and `assign`  compared having them in a dataframe.

For plotting we need a data frame with X and labels, but this can be constructed when it's needed inside `plot_clusters()` . 
How does this look?

0. `X_raw` = raw data expected to arrive as a dataframe

1. `X = precrocess(X_raw = dataframe)` returns an array

2.  `k =find_elbow(X = array)` returns an int

3.  `centers = fit(X = array, k=int)` returns an array of the cluster centers

4.  `X_clusters = assign(X = array, centers = array)` returns a list containing the cluster labels

5. `plot_clusters(X_clusters  = array, labels = list, centers = array)` returns a plot of the clusters with optional centers. We can use pd.DataFrame() to build the dataframe before passing it to the specific plotting function..

**Comment by mikelynch416** [comment]
If array type is easier for you then I'm ok to use it instead of DataFrame.

**Comment by sbabicki** [comment]
I'm fine with returning them as an array and list. 

We can create a helper function to assemble `X` and `labels` into a dataframe that can be called from within the `plot_centers` function. 

Are the data types for `X` correct in this? I thought `X` should remain as a dataframe the whole way through, not an array.

**Comment by sbabicki** [comment]
Also I think that `plot_centers` doesn't need to return anything. I expect it would just print the plot.

**Comment by trevorki** [comment]
Minor change:  the labels returned by `assign()` will be a 1d array, not a list

**Comment by sbabicki** [comment]
Are we good to close this issue now?

**Comment by trevorki** [comment]
yes!
