### ISSUE TITLE
fit_assign flake8 update

### ISSUE THREAD

**Issue by sbabicki** [UBC-MDS/kmeaningful#73]

**Comment by trevorki** [comment]
I fixed the formatting and it passes flake8, but now a test is failing because of a flake8 change
`if np.isnan(np.sum(current_center)) == False:` had to be changed to `if np.isnan(np.sum(current_center)) is False:`
And now if doesn't work the right way...
Working on it still

**Comment by sbabicki** [comment]
It's not working because the variable name can't be split over 2 lines.
Instead you can probably do something like:

if np.isnan(
    np.sum(current_center)
) == False

**Comment by trevorki** [comment]
Flake8 doesn't like `== False`
I changed it to `if not np.isnan(np.sum(current_center)):` and it works.

I'm still dealing with that branch coverage problem

**Comment by sbabicki** [comment]
Whoops, I saw this on my phone and it looked like you had put `current_` and `cluster` on two lines - hence my comment. Glad you got it working!
